# -*- coding: utf-8 -*-
"""SOP_EX5_AVAL1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uan5wEJqbT9BN7CS04I2gyjsaK1CFdc2
"""

#Instalar a biblioteca mysql

!pip install mysql-connector-python

#Importar a biblioteca
import mysql.connector

#Criar conexão
mydb = mysql.connector.connect(
  host="database-1.cbfqx5ljqmyu.us-east-1.rds.amazonaws.com",
  user="antonio",
  password="alunoantonio",

)

print(mydb)

#mycursor.execute("CREATE DATABASE prova_SOP")

#criar Data Base

uso_cpu = [
[20, 25, 40, 50, 45, 60, 55, 35, 70, 65],
[30, 35, 50, 60, 40, 55, 60, 45, 50, 55],
[15, 20, 30, 25, 35, 40, 45, 50, 55, 60],
[10, 15, 25, 35, 45, 50, 55, 60, 65, 70],
]

mycursor = mydb.cursor()

mycursor.execute("SHOW DATABASES")

import pandas as pd

colunas = [f"hora_{i+1}" for i in range(10)]

regioes = ["us-east-1", "us-west-2", "eu-central-1", "sa-east-1"]

df = pd.DataFrame(index=regioes, columns=colunas)

print(df)

